### PR TITLE
(#268) - pouchdb-auth update

### PR DESCRIPTION
**Pull request by marten-de-vries**
Switches from a session db to a cookie based session system, making user
document changes invalidate the session.

Needs testing and review. ~~https://github.com/pouchdb/pouchdb-auth/pull/4  needs to land first~~.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Seems like test-express-pouchdb fails in Travis due to 'pouchdb' not being found. Maybe having a dependency on 'pouchdb/pouchdb' (as this module does) doesn't call the new rollup script?

See https://travis-ci.org/pouchdb/express-pouchdb/jobs/102639768 for the failure; passes offline with the node_modules I still had installed:
```bash
marten@procyon:~/git/express-pouchdb$ npm run test-express-pouchdb

> express-pouchdb@1.0.1 test-express-pouchdb /home/marten/git/express-pouchdb
> mocha



  config
(node) warning: possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:179:15)
    at /home/marten/git/express-pouchdb/lib/replicator.js:60:17
    at tryCatcher (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/marten/git/express-pouchdb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
    ✓ should not create empty config file
    ✓ should have ./config.json as default config path
    ✓ should support setting a different config path
    ✓ should support externally adding a default (1533ms)
    ✓ should support externally getting a config value
    ✓ should support external listeners to a config change

  basics for /
    ✓ GET / should respond with a welcome page

  basics for /db/
    ✓ GET / should respond with a welcome page

  modes
    ✓ should always return a 404 in our custom configuration
    ✓ should generate a functioning core app
    ✓ should throw an error when given an invalid mode
    ✓ should throw an error when a not included part is excluded
    ✓ should throw an error when an unknown part is included

  redirects
    ✓ GET /_utils should redirect to /_utils/
    ✓ GET /_utils/ should return fauxton (58ms)


  15 passing (3s)

marten@procyon:~/git/express-pouchdb$ 
```

(although that event emitter limit might have to be upped a bit. But probably best to investigate that later. The PR is big enough as-is.)

**Comment by marten-de-vries** [comment]
Firefox seems permafail, but that's probably https://github.com/pouchdb/pouchdb/issues/4669 .

Performance is not much better or worse than previous it seems, that's good. Travis passes except for ^. In short: ready to merge. Although fixing Travis should really be the next priority.

**Comment by marten-de-vries** [comment]
Rebased; hopefully that'll make Travis pass completely.

**Comment by marten-de-vries** [comment]
Travis is green: https://github.com/pouchdb/express-pouchdb/pull/283

**Comment by marten-de-vries** [comment]
I think this is ready for merging, but I'd prefer not to timebomb it because of PR size. If anyone could give a quick look over, that would be nice. @gr2m @nolanlawson

**Comment by nolanlawson** [comment]
This looks good to me, although I'm not understanding why it's still red in Travis. I thought i had fixed the Firefox bug by removing the ETag logic.

**Comment by marten-de-vries** [comment]
Travis is very flakey, most of the other PRs for express-pouchdb time out on phantomjs.

I think this PR is still red because it hasn't been rebased since those fixes, you did that in #283.

**Comment by nolanlawson** [comment]
Ohhh right. Okay, then yeah, this is ready to merge. I'll do it.

**Comment by nolanlawson** [comment]
ef495aa4b5a9840400210adffba67af62aceb7af

**Comment by marten-de-vries** [comment]
Nice!

**Pull request closed without merging**
