### PR TITLE
update all old dependencies

### PR DESCRIPTION
**Pull request by garrensmith**

### CODE REVIEW

**Comment by nolanlawson** [comment]
:+1:

**Comment by mohlsen** [comment]
do we know when a new release might be dropped containing these dependency updates?

**Comment by garrensmith** [comment]
@mohlsen its already been released.

**Comment by mohlsen** [comment]
@garrensmith Looks like PR https://github.com/pouchdb/express-pouchdb/commit/459e185bc1184336aefcd49620bf7e471b3375d4 was accepted after v1.0.5 was released.  https://github.com/pouchdb/express-pouchdb/commits/master

Sorry if I dont understand something, but seems like the offical releases (on Github and npm) are v1.0.0 without this change.

**Comment by garrensmith** [comment]
Sorry @mohlsen you are correct. I've pushed a new release.

**Pull request merged**
