### PR TITLE
update Fauxton by switching to pouchdb-fauxton package

### PR DESCRIPTION
**Pull request by nolanlawson**
I created a new package called `pouchdb-fauxton` that simply runs a `prepublish` script to check out `couchdb-fauxton` from source, apply a few transformations to it, and then publish the result. Currently it's pegged to a particular git commit of `couchdb-fauxton` (the latest) but in the future that git commit can be updated and then Fauxton can be re-published. Hopefully in the future instead of doing search-and-replace we can just move to using configuration.

I've also overwritten the master on https://github.com/pouchdb/pouchdb-fauxton (the old master is on a branch called `older-master`).

The best way to test this change is to actually check out the code and see what Fauxton looks like; I'm very happy with it. :smiley:

/cc @nickcolley @garrensmith

### CODE REVIEW

**Comment by nolanlawson** [comment]
screenshot 2017-02-14 19 52 32

**Comment by nickcolley** [comment]
Not had a chance to check it out locally but this is excellent work! Thanks @nolanlawson 👍

**Comment by garrensmith** [comment]
+1 this is really cool. Nice work. I tested it and it looked great.
I'll use your replace script as a way to add in configuration into Fauxton.

**Comment by nolanlawson** [comment]
Meh, I wouldn't add the replace script itself to Fauxton. It's a hack; better would be to have variables inside the underscore template, i18n values, etc. :)

**Pull request merged**
