### PR TITLE
remove incorrect dbname encoding (part 2)

### PR DESCRIPTION
**Pull request by gr2m**
follow up for #377, sorry.

### CODE REVIEW

**Comment by gr2m** [comment]
I’m puzzled by the failing error. I can reproduce it locally when I run all tests, but not if I only run this single test or only tests in `tests/integration/test.basics.js`

I also can’t reproduce the problem using

```js
var PouchDB = require('pouchdb-core').plugin(require('pouchdb-adapter-leveldb'))
var db = new PouchDB('some%2Ftest')
db.info().then(function () { return db.destroy(); }).then(console.log).catch(console.log);
// { ok: true }
```

Same if I use the http adapter and test it against my CouchDB. And same if I start `express-pouchdb` locally with this script

```js
var express = require('express'),
    app     = express(),
    PouchDB = require('pouchdb')

app.use('/', require('express-pouchdb')(PouchDB));

app.listen(3000);
console.log('http://localhost:3000')
```

And run it against that. Here are the logs from the localhost:3000/_log

```
[Sun, 11 Sep 2016 21:45:58 GMT] [info] [<0.000.0>] ::ffff:127.0.0.1 - - GET /some%2Ftest/ 404
[Sun, 11 Sep 2016 21:45:58 GMT] [info] [<0.000.0>] ::ffff:127.0.0.1 - - PUT /some%2Ftest/ 201
[Sun, 11 Sep 2016 21:45:58 GMT] [info] [<0.000.0>] ::ffff:127.0.0.1 - - GET /some%2Ftest/ 200
[Sun, 11 Sep 2016 21:45:58 GMT] [info] [<0.000.0>] ::ffff:127.0.0.1 - - DELETE /some%2Ftest/ 200
```

halp ...

**Comment by nolanlawson** [comment]
have you tried node-inspector or node-nightly --debug? just from reading this comment, I'm not sure what's going on.

**Comment by gr2m** [comment]
@nolanlawson I never used `node-inspector` and run [into a problem](https://github.com/node-inspector/node-inspector/issues/905, downgrading to 6.3.1 does not fix it to me). I then tried `node --inspect --debug-brk` which seems to be supported in 6.5 and added a debugger to the test code, but couldn’t make the two work together. Any obvious hints?

**Comment by gr2m** [comment]
Okay I found what the problem is. Because I removed the encoding, it now tries to create database "testdbsome/test" instead of "testdbsome%2Ftest" in [lib/routes/db.js](https://github.com/pouchdb/express-pouchdb/blob/4d22dd4/lib/routes/db.js#L27-L35) and the error in line 30 is exactly the same as what we run into with Hoodie and worked around as described in https://github.com/pouchdb/pouchdb/issues/5668

I guess it’s time to look into pouchdb-adapter-leveldb, but I’ll put in the same workaround here to unblock express-pouchdb, it's in a faulty state right now because I removed the encoding in one place but not another. I’ll take ownership of this and make sure to remove the workaround once we have the assuring of folders in `pouchdb-adapter-leveldb` or `leveldown`

**Comment by nolanlawson** [comment]
I believe the right place to put this is in pouchdb-adapter-leveldb, although the problem then is that it becomes a breaking change in PouchDB itself. :/

Is it really crucial that Hoodie have this feature? Can you run express-pouchdb inside the folder where you want to write files?

**Comment by gr2m** [comment]
> Is it really crucial that Hoodie have this feature? Can you run express-pouchdb inside the folder where you want to write files?

Yes it’s a crucial feature, because people can create any databases they want, there will be more than just the `user/` folder. But we already worked around it in Hoodie as described in pouchdb/pouchdb#5668 and I’m just about to push the same workaround to express-pouchdb now, so there is no rush at all :) It's not a nice workaround, but it’s self-contained without side effects, and can easily be removed once we have the feature in `pouchdb-adapter-leveldb`.

**Comment by gr2m** [comment]
see https://github.com/pouchdb/express-pouchdb/pull/378/commits/44d5be841b759c5d6f781270a7d3094d84be5f02

**Comment by gr2m** [comment]
@nolanlawson all green ✌️ does that workaround work for you? Then I’d go ahead creating a CHANGELOG.md and release 2.0

**Comment by gr2m** [comment]
oh actually mind if we do changelogs in the wiki like you do in the pouchdb repo?

**Comment by gr2m** [comment]
> it becomes a breaking change in PouchDB itself

Actually when I think about it, how would that become a breaking change for PouchDB? The only difference would be that PouchDB will no longer throw an error if you try to `new PouchDB('my/db')` with the leveldb adapter, no?

**Comment by nolanlawson** [comment]
The mkdirp behavior is not breaking, but the encoding change is, right?

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson

**Comment by gr2m** [comment]
yes, but this only affects express-pouchdb, not pouchdb itself. And for express-pouchdb we do a breaking version update

**Comment by nolanlawson** [comment]
Ah ok I misunderstood. In that case, carry on. :)

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson

**Pull request merged**
