### PR TITLE
(#213) - allow HEAD requests to /:db/_all_docs

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Correct me if I'm wrong, but this is still going to send the full JSON body, right? I know the Etag is being set elsewhere, but I assume we want to return an empty body and just the headers.

**Comment by janl** [comment]
oh oops :D

**Comment by janl** [comment]
@nolanlawson you got me for not checking on that, but after checking, it turns out that express seems to do the right thing here:

```
> curl -I $COUCH/_users/_all_docs
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/plain; charset=utf-8
Content-Length: 359
ETag: W/"167-268ad8e3"
Vary: Accept-Encoding
Date: Thu, 28 May 2015 13:45:47 GMT
Connection: keep-alive

jan@rose ~ 
> curl  $COUCH/_users/_all_docs
{"total_rows":3,"offset":0,"rows":[{"id":"_design/_auth","key":"_design/_auth","value":{"rev":"1-a7b1ca50f51fe23525da081358f6677b"}},{"id":"_design/views","key":"_design/views","value":{"rev":"1-91b5781e7664d373a4ff64f3d6ff3265"}},{"id":"org.couchdb.user:user/a@a.a","key":"org.couchdb.user:user/a@a.a","value":{"rev":"2-f53998c66dd7bbad8acde6f4092a9509"}}]}
jan@rose ~ 
> curl -I $COUCH/_users/_all_docs
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/plain; charset=utf-8
Content-Length: 359
ETag: W/"167-268ad8e3"
Vary: Accept-Encoding
Date: Thu, 28 May 2015 13:45:57 GMT
Connection: keep-alive
```

**Comment by nolanlawson** [comment]
Oh sweet, Express is awesome! OK, let's merge this sucker, then. :)

**Comment by nolanlawson** [comment]
We should also probably add HEAD for `/db/doc`, which is where I've normally used HEAD. Didn't even realize that you could HEAD on `/all_docs`.

**Comment by janl** [comment]
In CouchDB, you can HEAD on almost everything :)

```
~/Work/couchdb/src/chttpd/src (master) 
> grep HEAD *.erl
chttpd.erl:    Method2 = case lists:member(MethodOverride, ["GET", "HEAD", "POST", "PUT", "DELETE", "TRACE", "CONNECT", "COPY"]) of
chttpd.erl:    % alias HEAD to GET as mochiweb takes care of stripping the body
chttpd.erl:        'HEAD' -> 'GET';
chttpd.erl:    'HEAD' -> throw({http_head_abort, Resp});
chttpd.erl:    'HEAD' -> throw({http_head_abort, Resp});
chttpd_auth_request.erl:  when Method =:= 'HEAD' orelse Method =:= 'GET' ->
chttpd_db.erl:    send_method_not_allowed(Req, "GET,POST,HEAD").
chttpd_db.erl:    send_method_not_allowed(Req, "DELETE,GET,HEAD,POST");
chttpd_db.erl:    send_method_not_allowed(Req, "GET,HEAD,POST");
chttpd_db.erl:    send_method_not_allowed(Req, "DELETE,GET,HEAD,POST,PUT,COPY").
chttpd_db.erl:    send_method_not_allowed(Req, "DELETE,GET,HEAD,PUT").
chttpd_misc.erl:    send_method_not_allowed(Req, "GET,HEAD").
chttpd_misc.erl:    send_method_not_allowed(Req, "GET,HEAD").
chttpd_misc.erl:    send_method_not_allowed(Req, "GET,HEAD").
chttpd_misc.erl:    send_method_not_allowed(Req, "GET,HEAD").
chttpd_misc.erl:    send_method_not_allowed(Req, "GET,HEAD").
chttpd_misc.erl:    send_method_not_allowed(Req, "GET,HEAD").
chttpd_show.erl:    chttpd:send_method_not_allowed(Req, "GET,POST,HEAD").
chttpd_view.erl:    chttpd:send_method_not_allowed(Req, "GET,POST,HEAD").
```

(The second `send_method_not_allowed` argument is a comma separated list of methods that **are** allowed)

**Comment by nolanlawson** [comment]
Interesting! I wonder if we can use these HEADs to speed up the replicator at all...

**Comment by nolanlawson** [comment]
merged as 9c21d2d7164d2375d6bb515fc004d06ac06ea3d8, thanks @janl !

**Pull request closed without merging**
