### PR TITLE
Update all deps

### PR DESCRIPTION
**Pull request by nolanlawson**
It's been awhile; let's see if we can just update nearly everything.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Tests failing due to something unrelated apparently:

```
  1) test.ajax.js-http #5061 ajax returns ETIMEDOUT error on timeout:

     Uncaught AssertionError: expected 'ESOCKETTIMEDOUT' to match /(ETIMEDOUT|ENETUNREACH|EAGAIN|ECONNREFUSED)/

      at tests/integration/test.ajax.js:19:25

      at Request._callback (packages/node_modules/pouchdb-for-coverage/lib/index.js:5437:14)

      at self.callback (node_modules/request/request.js:187:22)

      at ClientRequest.<anonymous> (node_modules/request/request.js:779:16)

      at Socket.socket.once (_http_client.js:566:38)

      at Socket._onTimeout (net.js:339:8)
```

**Comment by gr2m** [comment]
I get the same error when running tests on current master :(

**Comment by nolanlawson** [comment]
The fix is to use a frozen version of the PouchDB test suite. I'm working on this in my spare time

**Comment by nolanlawson** [comment]
Woot, green!

**Comment by gr2m** [comment]
This is great, thanks Nolan! <3

**Pull request merged**
