### PR TITLE
Update fauxton to 1.0.3

### PR DESCRIPTION
**Pull request by nickcolley**
Hopefully I did this right! :P

### CODE REVIEW

**Comment by nolanlawson** [comment]
Dang, it looks like Fauxton has really veered off from CouchDB 1.x. :( It seems we'll have to implement a cluster or faux-cluster API. I started on this [here](https://github.com/pouchdb/express-pouchdb/tree/update-fauxton-103-cluster-setup), but I'm not finished: 

screenshot from 2015-08-23 17 57 09

**Comment by nolanlawson** [comment]
It seems like we need a universal redirect of all URLs that start with `/_node/node@127.0.0.1/` to `/`, but I can't figure out how to do it. I tried a basic `app.use()`, but it's still failing. @marten-de-vries any ideas?

**Comment by nolanlawson** [comment]
BTW when I say "it's not working," I mean it seems like it's not even doing the redirect. When I replace `req.url` with a new URL, it appears to just ignore it.

**Comment by nolanlawson** [comment]
@nickcolley https://github.com/pouchdb/express-pouchdb/pull/245 should fix this PR.

**Comment by nolanlawson** [comment]
OK, one last fix! I rebuilt and added https://github.com/pouchdb/couchdb-fauxton/pull/9, and everything works now! Config, creating a user, even "Mango" queries! This is awesome!

**Comment by nolanlawson** [comment]
screenshot from 2015-08-23 20 55 37

**Comment by marten-de-vries** [comment]
Looks good, :+1: after squash and #245 is merged.

**Comment by nolanlawson** [comment]
f176580853d0caaa7b8f1d5030427d92d9d7c93a

**Comment by nolanlawson** [comment]
This is such a vast improvement, and some cursory testing indicates that it's working the same as before, so I'm just going to publish a new version of express-pouchdb. You can `npm install -g pouchdb-server` to get the latest.

**Pull request closed without merging**
