### PR TITLE
(#231, #250) - Re-introduce PouchDB.destroy()

### PR DESCRIPTION
**Pull request by marten-de-vries**
This reverts commit 2f6280d3c5cff5d96ca0a8cc2deeeac8811ebe26.

### CODE REVIEW

**Comment by nolanlawson** [comment]
OK strange, so pouchdb-wrappers adds `PouchDB.destroy()` back in? Is that why this works?

**Comment by nolanlawson** [comment]
Ah okay, read your other comment. LGTM, +1 when green.

**Comment by marten-de-vries** [comment]
> OK strange, so pouchdb-wrappers adds PouchDB.destroy() back in? Is that why this works?

Yes.

**Comment by nolanlawson** [comment]
Only failing in the tests we already knew were failing, so LGTM.

**Comment by nolanlawson** [comment]
3fb9af1c15b2b1a55234b684c8f4de1140dfafbf

**Pull request closed without merging**
