### PR TITLE
(#301) - massive greenkeeper update, pin deps

### PR DESCRIPTION
**Pull request by nolanlawson**
Consolidates all our recent Greenkeeper updates
and pins our dependencies. Hopefull this should be
green, then Greenkeeper will take care of the rest from
now on.

Why pin deps? Well, we're doing it in PouchDB core,
and mostly I'm just interested in shielding our users
from unexpected breakages. Pinning is safer.

### CODE REVIEW

**Comment by nickcolley** [comment]
:+1: when green

**Comment by gr2m** [comment]
Isn’t greenkeeper shielding you from broken patch / minor updates? This will create a ton of extra PRs by Greenkeeper, and if you don’t stay on top of it, won’t users end up with multiple versions of the same lib? Just wondering :)

**Comment by nolanlawson** [comment]
Our tests are flaky enough (Saucelabs goes down, etc.) that I'm not sure the "we'll tell you when something breaks" feature of Greenkeeper really works for us. Yes, it does create a lot of extra PRs, though. Currently we're kind of up to our ears in PRs on PouchDB proper, but I prefer keeping users protected from surprises.

E.g. imagine we set `"naughty-module": "^4.0.0" and then `4.0.1` has a breaking change, which is live in production for anybody who installs `express-pouchdb`. Pinning versions protects us from that (although not from deps of deps...).

That said, I'm open to suggestions. Currently Greenkeeper PRs are kinda overwhelming us in PouchDB. Also I don't find the "removing duplicates" argument very compelling, because it's a minor perf boost and assumes everybody is on the latest version of every library always.

**Comment by gr2m** [comment]
Yeah flaky tests is trouble :( Saucelabs, Selenium and friends are really hard to get stable :/

> everybody is on the latest version of every library always

that’s what ranges help with, don’t they?

**Comment by nolanlawson** [comment]
When I say "everyone" I mean all libraries and apps. Not easy to achieve. :/

This PR is passing everywhere except Phantom, which is disabled in master due to flakiness. So I'll merge.

**Pull request merged**
