### PR TITLE
(pouchdb/pouchdb-server#117) - set json type

### PR DESCRIPTION
**Pull request by nolanlawson**
Another attempt to fix pouchdb/pouchdb-server#117;
we'll see what Travis says.

### CODE REVIEW

**Comment by nolanlawson** [comment]
The Firefox test is still failing for the exact same reason as before. @daleharvey where did you change the content-type in order to get it to pass?

**Comment by daleharvey** [comment]
I added an unconditional Content-Type: application/json at the start of https://github.com/pouchdb/express-pouchdb/blob/master/lib/routes/changes.js#L5

**Comment by nolanlawson** [comment]
Shoot, I'm not able to reproduce locally anymore. All right, I'll just try the unconditional content-type.

**Comment by nolanlawson** [comment]
@daleharvey I just realized CouchDB itself is sending back `text/plain` for `_changes`. I don't think we've gotten to the bottom of this yet.

**Comment by daleharvey** [comment]
In the browser we send 'Accept: application/json' so it expects application/json back

    $ curl -X GET http://127.0.0.1:5984/testing/_changes -v -H "Accept: application/json"

You should be able to reproduce with `GREP=4094 SERVER=pouchdb-server CLIENT=selenium:firefox npm test', the test will run successfully, but there will be global errors in the console about not being well formed (json)

**Comment by nolanlawson** [comment]
Ah okay, I was testing with curl. I'll try again and see if I can find the fix.

**Comment by nolanlawson** [comment]
OK, tested locally and this should fix it.

**Comment by nolanlawson** [comment]
Looks like the content-type was a red herring. This is still failing in Travis.

That said, this is definitely a good fix, but we still don't know what's causing Firefox/Selenium to fail.

**Comment by nolanlawson** [comment]
This is still failing the Firefox test, but I'm going to self-+1 and publish so we can put to bed the theory that it's an issue with the content-type.

**Pull request merged**
