### PR TITLE
(#279) - make test logging less verbose

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by marten-de-vries** [comment]
:+1: when green.

**Comment by nolanlawson** [comment]
Ugggg, these Firefox tests just will not pass.

**Comment by nolanlawson** [comment]
Something is definitely broken with Firefox+Travis but I have no idea what.

**Comment by nolanlawson** [comment]
this still isn't green, but it's closer than it was before, so I'm going to call that a win and try to move on with fixing master later.

**Pull request merged**
