### PR TITLE
(#240) - allow GETing a user's document as the user

### LINKED ISSUE #240: GETting a user's document as the user returns a 404 missing
With CouchDB, If I have a user in my database, I can query their user document with their credentials:

    $ curl http://localhost:5984/_users/org.couchdb.user:test -u test:test
    {"_id":"org.couchdb.user:test", ...

In express-pouchdb this returns a 404 missing:

    $ curl http://localhost:3000/_users/org.couchdb.user:test -u test:test
    {"error":"not_found","reason":"missing"}

### PR DESCRIPTION
**Pull request by christophwitzko**
Hi everyone,

this pull request should close #240.

have a nice day,
Christoph

### CODE REVIEW

**Comment by christophwitzko** [comment]
Ping @nolanlawson

**Comment by nolanlawson** [comment]
Sorry for the late reply; I've been catching up on PRs this weekend. :sweat_smile:

So sadly we still don't have tests for this, but I tested locally and it's broken before but works after. Nice work! I will publish today.

```
express-pouchdb users-fetch-users (>'.')> curl -X GET "http://foobar:password@127.0.0.1:6984/_users/org.couchdb.user%3Afoobar"
{"name":"foobar","roles":[],"type":"user","iterations":10,"password_scheme":"pbkdf2","salt":"14115316a11d14e1e411d12a14b1ed17d1a91a017b1411eb","derived_key":"5a845d3d16fbe2b952e4b22ba5da1ea4cc49b5f3","_id":"org.couchdb.user:foobar","_rev":"1-d49e3550d1d7c9933ea86e9f07cfc0ad"}
express-pouchdb users-fetch-users <('.')> curl -X GET "http://127.0.0.1:6984/_users/org.couchdb.user%3Afoobar"
{"error":"not_found","reason":"missing"}
```

**Comment by nolanlawson** [comment]
published in 0.17.3

**Comment by christophwitzko** [comment]
Thank you! :+1: :relaxed:

**Pull request merged**
