### PR TITLE
Do not create empty config files

### PR DESCRIPTION
**Pull request by denis-sokolov**
Having a default config file is alright, but creating blank files seems meaningless and annoying.
Opinions?

### CODE REVIEW

**Comment by marten-de-vries** [comment]
I think this is indeed the right thing to do for the majority of users, and the implementation seems fine to me.

The tests should be handled differently though in my opinion: instead of removing the first one it could simply be made to pass by writing some config option to the file before checking if it exists. Same for the modified one. The 'should not create an empty file' test can then be added as a new test instead next to the existing ones. Is that doable @denis-sokolov?

**Comment by nolanlawson** [comment]
:+1: after tests passing, agree with @marten-de-vries about improving the tests tho

**Comment by denis-sokolov** [comment]
@nolanlawson, the tests are passing, I don't think the Travis failure is related to the PR.

@marten-de-vries, I have tried my best, but I am unable to refactor the tests the way you want to without bigger changes to the test file. I can't find out what config options I can set to check and I can't edit the app creation in `before` without affecting other tests.

I would argue that the previously existing tests are imperfect. Why do you need to ensure the app _creates_ a config files? You need to ensure whether the app _reads_ the config file, is that incorrect?

**Comment by marten-de-vries** [comment]
I did the tests like I wanted in #207, you're right that it was harder than it seemed to me initially due to the central app objects, but this should do it.

I did find out by the way that if you don't use one of the 'lighter' modes, visiting / will still generate a config file due to it needing to save the unique server uuid in the config file. But if you can avoid that, this should work fine.

**Comment by denis-sokolov** [comment]
Thanks!

**Comment by marten-de-vries** [comment]
33913192e553ca39bda6b4032a8604a70719d63a

**Pull request closed without merging**
