### PR TITLE
(#168) - Make JSON body parser limit configurable

### PR DESCRIPTION
**Pull request by marten-de-vries**

### CODE REVIEW

**Comment by yaronyg** [comment]
@marten-de-vries: Please help me out here. I want to +1 this but I'm not 100% clear on our requirements for a +1. Is it that I have looked at the code, understood what it does and think it looks fine. Is there any other requirement before saying +1?

Otherwise, +1 once it's green.

**Comment by marten-de-vries** [comment]
@yaronyg The only thing I check extra is the commit message format (& if it's a single commit unless that makes no sense in the situation). In this case both are ok so I'll take the :+1:. Thanks for the review! :)

**Comment by marten-de-vries** [comment]
And it's green (#180 for the proof since Travis is currently broken without a small extra fix).

**Comment by marten-de-vries** [comment]
Note: master won't pass Travis until #181 is merged, the change itself has been tested in #180 though so that shouldn't be a problem.

**Pull request merged**
