### PR TITLE
(#191) - No temp views in minimumForPouchDB mode

### PR DESCRIPTION
**Pull request by marten-de-vries**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Rebased for you, so we can test `minimum-for-pouchdb`.

**Comment by marten-de-vries** [comment]
... which was a good idea considering it fails. Seems like there's another temp view used in the pouchdb test suite that hasn't been removed yet. Until that happens, this shouldn't be merged. The rate things are going, we can either keep this open for a while or I can submit this again later.

**Comment by nolanlawson** [comment]
Yeah, I just noticed a test where we say `ifCouchMaster() { /* skip test */}`. Since PouchDB Server obviously isn't CouchDB master, the  test would fail.

Personally I am kinda -0 on this PR; it doesn't really make any sense to me why we would remove temp views from the `minimumForPouchDB` mode, given that the PouchDB `http` adapter itself has a `query()` function which normally allows temp views.

**Comment by marten-de-vries** [comment]
Ok, I'm going to close this and open a new PR that doesn't disable temp views, but does separate it out in its own file so we can deprecate it more easily later if needed, or remove it from specific profiles.

**Pull request closed without merging**
