### PR TITLE
Changing response status from 200 to 202

### PR DESCRIPTION
**Pull request by Nullpo**
FIxes #227

I didn't know from which branch start. I used "4669", but if is other, please tell me :).

### CODE REVIEW

**Comment by gr2m** [comment]
@Nullpo can you please send the pull request against the new monorepo: https://github.com/pouchdb/pouchdb-server/blob/master/packages/node_modules/express-pouchdb/lib/routes/compact.js

This repository will be removed

**Comment by nolanlawson** [comment]
Yes I'm sorry, this repository is deprecated. I tried to be clear in the README, but I also wanted to keep the issues/PRs open in case people wanted to browse the old ones. 🙂

Please see https://github.com/pouchdb/pouchdb-server/ and in particular https://github.com/pouchdb/pouchdb-server/blob/master/packages/node_modules/express-pouchdb/lib/routes/compact.js . I'll close this issue, but please do open a new one in the other repo. 🙂

**Comment by nolanlawson** [comment]
Updated the README to make it clearer. Sorry about that!

**Comment by nolanlawson** [comment]
Sorry, somebody got to it before you. 🙁 https://github.com/pouchdb/pouchdb-server/pull/204 Plenty more issues remain, though! :smiley:

**Pull request closed without merging**
