### PR TITLE
(#187) - Show/list/update couchdb-harness fixes

### PR DESCRIPTION
**Pull request by marten-de-vries**
Needs https://github.com/pouchdb/couchdb-harness/pull/17 (and the other couchdb-harness fixes) merged before test-couchdb will pass.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Valid Travis failure. I think I've got a fix.

**Comment by marten-de-vries** [comment]
Ok, with Travis (going to be) passing (incl. test-couchdb) this is ready to be considered for merging again.

**Comment by nolanlawson** [comment]
+1 when green

**Comment by nolanlawson** [comment]
ah wait, it's green

**Pull request merged**
