### PR TITLE
(#218) add db name to userCtx

### PR DESCRIPTION
**Pull request by tyler-johnson**
I ran tests and all seemed to be good other than `test-pouchdb-minimum` which failed with a bunch of `Bad option: 'futurehostile'.` Also I'm not totally sure this is the best way to extract the name but I figured this is a good starting point.

### CODE REVIEW

**Comment by nolanlawson** [comment]
`Bad option: 'futurehostile'.` is because of an old version of jshint.

**Comment by nolanlawson** [comment]
This is breaking the `minimum-for-pouchdb` test:

    test.all_docs.js-http
    TypeError: Cannot set property 'db' of undefined
        at Object.exports.makeOpts (/home/travis/build/pouchdb/express-pouchdb/lib/utils.js:54:21)
        at /home/travis/build/pouchdb/express-pouchdb/lib/routes/documents.js:16:22
        at Layer.handle [as handle_request] (/home/travis/build/pouchdb/express-pouchdb/node_modules/express/lib/router/layer.js:82:5)

If you rebase on master and then re-push you can test the breakage yourself. Sorry that the tests were so flakey back when you created this PR.

**Comment by tyler-johnson** [comment]
Alright, I pushed those changes and it appears everything is passing.

**Comment by nolanlawson** [comment]
LGTM, thanks!

**Comment by nolanlawson** [comment]
Small mistake with the commit message (missing hyphen), but squashed and merged as 841f75f8f33e5f356792ee5f123605903fcbaafd. Thanks again!

**Pull request closed without merging**
