### PR TITLE
(#4240) - Send json content-type over text/plain

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by nolanlawson** [comment]
+1 when green, really surprised this went undetected for so long

**Comment by marten-de-vries** [comment]
Why do this? CouchDB seems to send text unless requested otherwise too (and that's probably tested by couchdb-harness, meaning that would get regressed further).

```bash
marten@procyon:~$ curl http://localhost:5984/test -v
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5984 (#0)
> GET /test HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:5984
> Accept: */*
> 
< HTTP/1.1 404 Object Not Found
* Server CouchDB/1.6.0 (Erlang OTP/17) is not blacklisted
< Server: CouchDB/1.6.0 (Erlang OTP/17)
< Date: Sat, 05 Sep 2015 15:36:44 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 44
< Cache-Control: must-revalidate
< 
{"error":"not_found","reason":"no_db_file"}
* Connection #0 to host localhost left intact
marten@procyon:~$ 
```

**Comment by daleharvey** [comment]
You are right, surprised at that, but something about how the detection is made is done differently and it is causing pouchdb-server to fail the test suite in travis - https://github.com/pouchdb/pouchdb/issues/4240

**Comment by marten-de-vries** [comment]
So if I read that issue correctly, the actual bug is that ``/_changes`` doesn't always handle the content type correctly. Considering the other stuff is ok ('following CouchDB behaviour'), can we just patch that like suggested earlier in these two comments?

https://github.com/pouchdb/pouchdb/issues/4240#issuecomment-137089124
https://github.com/pouchdb/pouchdb/issues/4240#issuecomment-137092223

**Comment by nolanlawson** [comment]
I'm fine with whatever we need to do to get PouchDB Server to pass the Firefox tests again. If we just patch `_changes` then I'm fine with that.

Speaking of which, according to Travis this PR actually doesn't fix the bug; Firefox is still failing.

**Comment by marten-de-vries** [comment]
> Speaking of which, according to Travis this PR actually doesn't fix the bug; Firefox is still failing.
That actually makes sense: ``/_changes`` doesn't use ``utils.sendJSON()`` because it needs ``res.write()`` (the streaming API). So this change wouldn't influence it anyway.

**Comment by marten-de-vries** [comment]
Closing this out in favour of #254. Feel free to re-open if you disagree with that approach, @daleharvey.

**Pull request closed without merging**
