### PR TITLE
Add post to views route

### LINKED ISSUE #215: couchdb supports POST on views, express-pouchdb does not
Couchdb supports POST requests for views. (i.e. `/dbname/_design/designDocName/_view/viewName`) but express-pouchdb only supports GET.

I cam across this because the nano library takes advantage of this when the 'keys' query option is used. 

Pull request with a fix for this is incoming.

### PR DESCRIPTION
**Pull request by robotlovesyou**
Fixes #215

### CODE REVIEW

**Comment by robotlovesyou** [comment]
Oh PS, since there aren't any tests for the existing route, I didn't add any here. Happy to add some if necessary though.

**Comment by nolanlawson** [comment]
LGTM, thanks! I believe our system for testing would be to enable some disabled test in the CouchDB suite, although I'd have to check with @marten-de-vries.

**Comment by robotlovesyou** [comment]
Ah I see now. So those would be in [couchdb-harness](https://github.com/pouchdb/couchdb-harness)?

**Comment by marten-de-vries** [comment]
I gave the couchdb-harness tests a quick look, there are POSTs to views inside there, but the ones I could find would probably still crash on other stuff. E.g.:

- https://github.com/pouchdb/couchdb-harness/blob/master/javascript/tests/etags_views.js#L160
- https://github.com/pouchdb/couchdb-harness/blob/master/javascript/tests/view_errors.js#L162

For now, I'm in favour of just merging without tests. We know there are no regressions in the pouchdb + the couchdb-harness tests that are run, that's good enough.

Enabling more of couchdb-harness would still be welcome, of course, but that's a separate project.

**Comment by nolanlawson** [comment]
@marten-de-vries we're going to start testing mapreduce against pouchdb-server soon, so that's also a good test. I'm +1 to merge.

**Comment by marten-de-vries** [comment]
Squashed + merged. I forgot to include the issue number in the commit message, but nothing to do about that now without a revert + recommit, which is probably not worth the hassle. 401689275c50b225bfb4568cc0b59bf09d2b4be4

Thanks @robotlovesyou!

**Comment by nolanlawson** [comment]
Nope, not worth the hassle. :) Nice!

**Pull request closed without merging**
