### PR TITLE
(#122) - Mode support (custom, minimumForPouchDB & fullCouchDB)

### PR DESCRIPTION
**Pull request by marten-de-vries**
Adds the following options:
- profile
- profileDiff
 - include
 - exclude

This allows users to specify exactly which parts of express-pouchdb need to be loaded. Dependencies are handled by a check to ``app.includes[partThatsNeeded]``, often abstracted away via ``utils.requires``.

The order in which the routes are loaded is specified by index.js.

See for examples on how to use the included tests. The second argument ('opts') needs to be documented in README.md though.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
The commit above gets the code up-to-date with everything discussed so far. (snake_case -> kebab-case for files, profile -> mode, profileDiff -> overrideMode, core -> minimumForPouchDB & complete -> fullCouchDB).

**Comment by marten-de-vries** [comment]
Oh, forgot to modify the commit message to use 'mode' instead of 'profile'. That can be fixed when merging.

**Comment by nolanlawson** [comment]
+1

**Comment by marten-de-vries** [comment]
Merged: 3920710f2ef09b6fbadac65983a9cdc2bd0ba6e3

**Pull request closed without merging**
