### PR TITLE
(pouchdb/server#108) - fix compact()

### PR DESCRIPTION
**Pull request by nolanlawson**
Get rid of the hack, which I'm not sure
why we were using in the first place.

### CODE REVIEW

**Comment by nolanlawson** [comment]
I manually verified that this is passing the full test suite BTW. Although until #226 is merged, we won't be able to prove it through Travis.

**Comment by daleharvey** [comment]
https://github.com/pouchdb/express-pouchdb/pull/178 is the original reasoning, but getting rid of a setTimeout is always the right thing to do, :+1: from me

**Comment by nolanlawson** [comment]
c0849dda31e347f1c75a4a0d110842c16ede78da

**Comment by marten-de-vries** [comment]
This is a regression for couchdb-harness. I'm ok with removing the setTimeout hack, but this does break CouchDB compat so in that case we probably want a different 'return early' solution.

```
    Error: false
Trace back (most recent call first):
    
  52: /home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb-server/node_modules/couchdb-harness/javascript/test_setup.js
      T(false)
  57: /home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb-server/node_modules/couchdb-harness/javascript/tests/compact.js
      ()
  39: /home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb-server/node_modules/couchdb-harness/javascript/cli_runner.js
      runTest()
  50: /home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb-server/node_modules/couchdb-harness/javascript/cli_runner.js
```

**Comment by nolanlawson** [comment]
Ah crap, I didn't notice that. What does the setTimeout hack fix, exactly?

**Comment by marten-de-vries** [comment]
Properties of /_compact are:
- It returns 202 instead of 200.
- It returns as soon as the compaction action has been started, but doesn't wait for it to finish.

setTimeout was a hack that happened to kind of work: any security code (e.g. are you a db admin?) was run before its callback was called and in that case an error was returned. If it was called, that meant the database had started compaction, and thus a positive ('202') response could be generated without waiting for it to finish.

**Comment by nolanlawson** [comment]
So can we fix this by just returning 202? I don't think it's a big deal to wait for compaction to finish.

**Comment by marten-de-vries** [comment]
For couchdb-harness, we could probably get away with that. It might be annoying for non-JS clients though, if requests are blocking and the user experience would be degraded.

That said, fine with me to solve it that way for now, we can always improve on it later.

**Comment by nolanlawson** [comment]
Cool, let's open an issue to do that then.

**Pull request closed without merging**
